apiVersion: v1
kind: Service
metadata:
  name: edge-kafka-backend-service
spec:
  type: NodePort
  selector:
    app: edge-kafka-backend
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30400
