apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-kafka-backend-deployment
spec:
  selector:
    matchLabels:
      app: edge-kafka-backend
  template:
    metadata:
      labels:
        app: edge-kafka-backend
    spec:
      containers:
      - name: edge-kafka-backend
        image: edge-kafka-backend:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
